name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET Framework Developer Pack
      run: |
        choco install netfx-4.5.2-devpack -y

    - name: Restore dependencies
      run: msbuild /t:restore SoftwareModem.sln

    - name: Build solution
      run: msbuild SoftwareModem.sln /p:Configuration=Release

    - name: Publish binaries
      run: msbuild SoftwareModem.sln /p:Configuration=Release /p:OutputPath=./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SoftwareModem
        path: ./publish

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: SoftwareModem

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: SoftwareModem
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.0
        name: SoftwareModem v1.0.0
        body: |
          Initial release of the SoftwareModem project.
